### ISSUE TITLE
For what reason search by City returns also other cities

### ISSUE THREAD

**Issue by aahutsal** [gutsal-arsen/raphael-elvanto#16]
![xxx](https://cloud.githubusercontent.com/assets/1643117/14582986/c3cc6ec0-041d-11e6-8007-ba658fd13af8.jpg)

**Comment by vitalyp** [comment]
What I know for now, the reason is locations array:
{
  "_id": "56febf70179359d576b1f082",
  "firstname": "Tamer",
  "lastname": "Abdelsayed",
  "phone": "",
  "mobile": "(951) 500-7545",
  "gender": "Male",
  "home_address": "5488 Serenity Place Apartment C",
  "home_city": "Corona",
  "home_postcode": "92880",
  "loc": [
    -110.8174741,
    31.971539
  ]
}

most of matched contacts has such loc value:
"loc": [
    -117.51
    33.8
  ]
